baseURL = 'https://configism.com/'
title = 'Configism — Philosophical Movement and Discipline of Thought'
theme = 'hugo-book'
defaultContentLanguage = 'en'

[params]
  description = 'Configism is an architectural model of reality perception based on the algorithmic analysis of the Universe. Configism provides CER and LR tools for deconstructing social matrices and the conscious evolution of the Spark. Everything is a Config.'
  BookSearch = true
  BookMenuBundle = '/menu'
  BookSectionEnumerable = true

[menu]
  # Це посилання, які СТВОРЮЮТЬ меню зліва
  [[main]]
    name = "Manifest"
    url = "/docs/manifest/"
    weight = 10
  [[main]]
    name = "PNL & LR"
    url = "/docs/pnl-lr/"
    weight = 20
