baseURL = 'https://configism.com/'
title = 'Configism'
theme = 'hugo-book'
defaultContentLanguage = 'en'

[params]
  description = 'Everything is a Config.'
  BookSearch = true
  BookMenuBundle = '/menu'
  BookSectionEnumerable = true
  BookAnchorCopy = false
