baseURL = 'https://configism.com/'
title = 'CONFIGISM'
theme = 'hugo-book'
defaultContentLanguage = 'en'

# Важливо для теми Book
[params]
  BookSearch = true
  BookMenuBundle = '/menu'
  BookSectionEnumerable = true

[menu]
  # Це посилання, які СТВОРЮЮТЬ меню зліва
  [[main]]
    name = "Manifest"
    url = "/docs/manifest/"
    weight = 10
  [[main]]
    name = "PNL & LR"
    url = "/docs/pnl-lr/"
    weight = 20
