baseURL = 'https://configism.com/'
title = 'title'
theme = 'hugo-book'
defaultContentLanguage = 'en'
enableRobotsTXT = false

[params]
  description = 'description'
  BookSearch = true
  BookMenuBundle = '/menu'
  BookSectionEnumerable = true
  BookAnchorCopy = false

[permalinks]
  docs = '/:title/'
