name = "Hugo Book"
license = "MIT"
licenselink = "github.com"
description = "Hugo documentation theme as simple as plain book"
homepage = "http://example.com/"
tags = ["documentation", "book", "mobile-first"]
features = ["search", "multilingual"]

[author]
  name = "Alex Shpak"
  homepage = "github.com"
